routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('', \App\Http\Controllers\PortfolioController::class);






Route::middleware(['auth'])->group(function () {
    Route::resource('facts', \App\Http\Controllers\FactsController::class);

});









Auth::routes([
    'register'=> false
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');






Route::post('message', function (\Illuminate\Http\Request $request){

    \Illuminate\Support\Facades\Http::post('https://api.telegram.org/bot5690769846:AAG_cxywUHiqI4NL-zgU0BUbKBuJqcXrhbU/sendMessage', [
        'chat_id'=>5412362990,
        'text'=>'Name: '.$request->name.' '.' Email: '.$request->email. ' '.
            ' Text: '.$request->text. ' '
            .' Message: '.$request->message. ' ',
//        'parse_mode'=>'html'
    ]);

    return redirect()->route('index');


})->name('message');

app/Models/Facts.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Facts extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $table = 'facts';
    protected $fillable = [
        'id',
        'image',
        'number',
        'text',
        'text_2',
    ];
}

app/Http/Controllers/FactsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Facts;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class FactsController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->text){
            $search = $request->text;
//            $facts = Facts::where('text','like','%'.$request->text.'%')->get();
            $facts = DB::table('facts as f')
                ->where('f.text','like','%'.$request->text.'%')
                ->select('f.*')->get();
        }else{
            $facts = Facts::all();
            $search = '';
        }



        return view('admin.facts.index',compact('facts','search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'number'=>'required',
            'text'=>'required',
            'text_2'=>'required',
            'image'=>'required',
        ]);

        Facts::create([
            'number'=> $request->number,
            'text'=>$request->text,
            'text_2'=>$request->text_2,
            'image'=>$request->image,
        ]);

        return redirect()->route('facts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function pay($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $fact = Facts::find($id);
        $fact->delete();

        return redirect()->route('facts.index');

    }
}

resources/views/admin/facts/index.blade.php
@extends('admin.layouts.app')



@section("main")

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <div class="row">
                        <div class="col-8">
                            <h4 class="card-title">Facts</h4>
                        </div>

                        <div class="col-4">
                            <!-- App Search-->
                            <form action="{{ route('facts.index') }}" class="app-search py-0 d-none d-lg-block">
                                <div class="position-relative">
                                    <input type="text" class="form-control" name="text" placeholder="Search..." value="{{ $search }}">
                                    <span class="bx bx-search-alt"></span>
                                </div>
                            </form>
                        </div>
                    </div>

                    @if(count($facts) != 0)

                    <div class="table-rep-plugin">
                        <div class="table-responsive mb-0" data-pattern="priority-columns">
                            <table id="tech-companies-1" class="table table-striped">
                                <thead>
                                <tr>
                                    <th>N</th>
                                    <th data-priority="1">Number</th>
                                    <th data-priority="1">Image</th>
                                    <th data-priority="3">Text bold</th>
                                    <th data-priority="1">Text</th>
                                    <th>
                                        <!-- Button trigger modal -->
                                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                            Create
                                        </button>

                                        <!-- Modal -->
                                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel">Create facts</h5>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                    </div>
                                                    <form action="{{ route('facts.store') }}" method="post">
                                                        @csrf
                                                        @method('POST')
                                                        <div class="modal-body">
                                                            <label for="number" class="form-label">Number</label>
                                                            <input required type="number" class="form-control" id="number" name="number" placeholder="Number">

                                                            <label for="text" class="form-label">Text</label>
                                                            <input required type="text" class="form-control" id="text" name="text" placeholder="Text">

                                                            <label for="text_2" class="form-label">Simple text</label>
                                                            <input required type="text_2" class="form-control" id="text_2" name="text_2" placeholder="Simple text">

                                                            <label for="image" class="form-label">Image</label>
                                                            <input required type="text" class="form-control" id="image" name="image" placeholder="image">
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                                            <button type="submit" class="btn btn-primary">Save</button>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($facts as $fact)
                                <tr>
                                    <th>{{ $fact->id }}</th>
                                    <td>{{ $fact->number }}</td>
                                    <td>{{ $fact->image }}</td>
                                    <td>{{ $fact->text }}</td>
                                    <td>{{ $fact->text_2 }}</td>
                                    <td>
                                        <!-- Button trigger modal -->
                                        <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#delete{{ $fact->id }}">
                                            Delete
                                        </button>

                                        <!-- Modal -->
                                        <div class="modal fade" id="delete{{ $fact->id }}" tabindex="-1" aria-labelledby="delete{{ $fact->id }}" aria-hidden="true">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel">Create facts</h5>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                    </div>
                                                    <form action="{{ route('facts.destroy', $fact->id) }}" method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                        <div class="modal-body">
                                                            <h3>Are you sure?</h3>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                                            <button type="submit" class="btn btn-danger">Delete</button>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach

                                </tbody>
                            </table>
                        </div>

                    </div>

                    @else

                        <h1 class=" text-center">Malumot topilmadi</h1>

                    @endif

                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->


@endsection